let data = [{
        "Country": "Afghanistan",
        "Happiness_Score": "1.859",
        "GDP_per_capita": "7.324",
        "Social_support": "0.341",
        "Healthy_life_expectancy": "54.712",
        "Corruption": "0.847",
        "Id": "1",
        "Freedom_Score": "0",
        "Property_Rights": "5.8",
        "Government_Spending": "0",
        "Business": "34.6",
        "Trade": "0",
        "Investment": "0",
        "rank": "4",
        "Crime_Index": "76",
        "Population": "42239854"
    },
    {
        "Country": "Albania",
        "Happiness_Score": "5.277",
        "GDP_per_capita": "9.567",
        "Social_support": "0.718",
        "Healthy_life_expectancy": "69.15",
        "Corruption": "0.878",
        "Id": "2",
        "Freedom_Score": "65.3",
        "Property_Rights": "55.9",
        "Government_Spending": "71",
        "Business": "70.7",
        "Trade": "82.8",
        "Investment": "70",
        "rank": "78",
        "Crime_Index": "43",
        "Population": "2832439"
    },
    {
        "Country": "Algeria",
        "Happiness_Score": "5.329",
        "GDP_per_capita": "9.3",
        "Social_support": "0.855",
        "Healthy_life_expectancy": "66.549",
        "Corruption": "0.717",
        "Id": "3",
        "Freedom_Score": "43.2",
        "Property_Rights": "27.8",
        "Government_Spending": "50.7",
        "Business": "53.6",
        "Trade": "57.5",
        "Investment": "30",
        "rank": "43",
        "Crime_Index": "52",
        "Population": "45606480"
    },
    {
        "Country": "Argentina",
        "Happiness_Score": "6.024",
        "GDP_per_capita": "9.959",
        "Social_support": "0.891",
        "Healthy_life_expectancy": "67.2",
        "Corruption": "0.814",
        "Id": "5",
        "Freedom_Score": "51",
        "Property_Rights": "34.6",
        "Government_Spending": "53.9",
        "Business": "55.5",
        "Trade": "61.2",
        "Investment": "55",
        "rank": "18",
        "Crime_Index": "64",
        "Population": "45773884"
    },
    {
        "Country": "Armenia",
        "Happiness_Score": "5.342",
        "GDP_per_capita": "9.615",
        "Social_support": "0.79",
        "Healthy_life_expectancy": "67.789",
        "Corruption": "0.705",
        "Id": "6",
        "Freedom_Score": "65.1",
        "Property_Rights": "50.3",
        "Government_Spending": "76.3",
        "Business": "64.9",
        "Trade": "73.6",
        "Investment": "75",
        "rank": "127",
        "Crime_Index": "23",
        "Population": "2777970"
    },
    {
        "Country": "Australia",
        "Happiness_Score": "7.095",
        "GDP_per_capita": "10.821",
        "Social_support": "0.934",
        "Healthy_life_expectancy": "71.05",
        "Corruption": "0.496",
        "Id": "7",
        "Freedom_Score": "74.8",
        "Property_Rights": "90.7",
        "Government_Spending": "47",
        "Business": "88.3",
        "Trade": "89.8",
        "Investment": "80",
        "rank": "75",
        "Crime_Index": "43",
        "Population": "26439111"
    },
    {
        "Country": "Austria",
        "Happiness_Score": "7.097",
        "GDP_per_capita": "10.899",
        "Social_support": "0.888",
        "Healthy_life_expectancy": "71.15",
        "Corruption": "0.497",
        "Id": "8",
        "Freedom_Score": "71.1",
        "Property_Rights": "97",
        "Government_Spending": "13",
        "Business": "78.5",
        "Trade": "78.6",
        "Investment": "80",
        "rank": "119",
        "Crime_Index": "26",
        "Population": "8958960"
    },
    {
        "Country": "Bahrain",
        "Happiness_Score": "6.173",
        "GDP_per_capita": "10.776",
        "Social_support": "0.844",
        "Healthy_life_expectancy": "65.825",
        "Corruption": "0.737",
        "Id": "11",
        "Freedom_Score": "62.5",
        "Property_Rights": "65.4",
        "Government_Spending": "66.3",
        "Business": "64",
        "Trade": "84.2",
        "Investment": "85",
        "rank": "118",
        "Crime_Index": "26",
        "Population": "1485509"
    },
    {
        "Country": "Bangladesh",
        "Happiness_Score": "4.282",
        "GDP_per_capita": "8.685",
        "Social_support": "0.544",
        "Healthy_life_expectancy": "64.548",
        "Corruption": "0.698",
        "Id": "12",
        "Freedom_Score": "54.4",
        "Property_Rights": "36.8",
        "Government_Spending": "94.7",
        "Business": "56.7",
        "Trade": "62",
        "Investment": "50",
        "rank": "17",
        "Crime_Index": "64",
        "Population": "172954319"
    },
    {
        "Country": "Belgium",
        "Happiness_Score": "6.859",
        "GDP_per_capita": "10.844",
        "Social_support": "0.915",
        "Healthy_life_expectancy": "70.899",
        "Corruption": "0.549",
        "Id": "15",
        "Freedom_Score": "67.1",
        "Property_Rights": "92",
        "Government_Spending": "8.1",
        "Business": "79",
        "Trade": "78.6",
        "Investment": "85",
        "rank": "70",
        "Crime_Index": "45",
        "Population": "11686140"
    },
    {
        "Country": "Bolivia",
        "Happiness_Score": "5.684",
        "GDP_per_capita": "8.985",
        "Social_support": "0.811",
        "Healthy_life_expectancy": "63.599",
        "Corruption": "0.846",
        "Id": "19",
        "Freedom_Score": "43.4",
        "Property_Rights": "21.1",
        "Government_Spending": "60.8",
        "Business": "55.1",
        "Trade": "60",
        "Investment": "15",
        "rank": "27",
        "Crime_Index": "58",
        "Population": "12388571"
    },
    {
        "Country": "Bosnia and Herzegovina",
        "Happiness_Score": "5.633",
        "GDP_per_capita": "9.616",
        "Social_support": "0.88",
        "Healthy_life_expectancy": "67.275",
        "Corruption": "0.918",
        "Id": "20",
        "Freedom_Score": "62.9",
        "Property_Rights": "48.2",
        "Government_Spending": "46.6",
        "Business": "67",
        "Trade": "68",
        "Investment": "65",
        "rank": "76",
        "Crime_Index": "43",
        "Population": "3210847"
    },
    {
        "Country": "Botswana",
        "Happiness_Score": "3.435",
        "GDP_per_capita": "9.629",
        "Social_support": "0.753",
        "Healthy_life_expectancy": "54.725",
        "Corruption": "0.83",
        "Id": "21",
        "Freedom_Score": "64.9",
        "Property_Rights": "72.8",
        "Government_Spending": "61.1",
        "Business": "65.2",
        "Trade": "78.6",
        "Investment": "65",
        "rank": "42",
        "Crime_Index": "53",
        "Population": "2675352"
    },
    {
        "Country": "Brazil",
        "Happiness_Score": "6.125",
        "GDP_per_capita": "9.582",
        "Social_support": "0.836",
        "Healthy_life_expectancy": "65.749",
        "Corruption": "0.738",
        "Id": "22",
        "Freedom_Score": "53.5",
        "Property_Rights": "49.7",
        "Government_Spending": "55",
        "Business": "63.6",
        "Trade": "65",
        "Investment": "60",
        "rank": "9",
        "Crime_Index": "67",
        "Population": "216422446"
    },
    {
        "Country": "Bulgaria",
        "Happiness_Score": "5.466",
        "GDP_per_capita": "10.087",
        "Social_support": "0.918",
        "Healthy_life_expectancy": "66.5",
        "Corruption": "0.911",
        "Id": "23",
        "Freedom_Score": "69.3",
        "Property_Rights": "75.3",
        "Government_Spending": "56.5",
        "Business": "71.8",
        "Trade": "78.6",
        "Investment": "60",
        "rank": "92",
        "Crime_Index": "38",
        "Population": "6687717"
    },
    {
        "Country": "Cambodia",
        "Happiness_Score": "4.393",
        "GDP_per_capita": "8.385",
        "Social_support": "0.747",
        "Healthy_life_expectancy": "61.9",
        "Corruption": "0.857",
        "Id": "27",
        "Freedom_Score": "56.5",
        "Property_Rights": "40.8",
        "Government_Spending": "78.7",
        "Business": "54.4",
        "Trade": "66.8",
        "Investment": "50",
        "rank": "46",
        "Crime_Index": "51",
        "Population": "16944826"
    },
    {
        "Country": "Cameroon",
        "Happiness_Score": "4.973",
        "GDP_per_capita": "8.217",
        "Social_support": "0.686",
        "Healthy_life_expectancy": "55.847",
        "Corruption": "0.846",
        "Id": "28",
        "Freedom_Score": "51.9",
        "Property_Rights": "38.4",
        "Government_Spending": "91.1",
        "Business": "47.2",
        "Trade": "53.6",
        "Investment": "30",
        "rank": "14",
        "Crime_Index": "65",
        "Population": "28647293"
    },
    {
        "Country": "Canada",
        "Happiness_Score": "6.961",
        "GDP_per_capita": "10.773",
        "Social_support": "0.929",
        "Healthy_life_expectancy": "71.4",
        "Corruption": "0.42",
        "Id": "29",
        "Freedom_Score": "73.7",
        "Property_Rights": "88.5",
        "Government_Spending": "35",
        "Business": "87.9",
        "Trade": "83.4",
        "Investment": "80",
        "rank": "82",
        "Crime_Index": "42",
        "Population": "38781291"
    },
    {
        "Country": "Chile",
        "Happiness_Score": "6.334",
        "GDP_per_capita": "10.114",
        "Social_support": "0.889",
        "Healthy_life_expectancy": "70.3",
        "Corruption": "0.823",
        "Id": "33",
        "Freedom_Score": "71.1",
        "Property_Rights": "72.3",
        "Government_Spending": "73.5",
        "Business": "75.7",
        "Trade": "78",
        "Investment": "70",
        "rank": "41",
        "Crime_Index": "53",
        "Population": "19629590"
    },
    {
        "Country": "China",
        "Happiness_Score": "5.818",
        "GDP_per_capita": "9.738",
        "Social_support": "0.836",
        "Healthy_life_expectancy": "68.689",
        "Corruption": "0.727",
        "Id": "34",
        "Freedom_Score": "48.3",
        "Property_Rights": "45.3",
        "Government_Spending": "65.1",
        "Business": "68.3",
        "Trade": "73.6",
        "Investment": "20",
        "rank": "108",
        "Crime_Index": "30",
        "Population": "1425671352"
    },
    {
        "Country": "Colombia",
        "Happiness_Score": "5.63",
        "GDP_per_capita": "9.584",
        "Social_support": "0.822",
        "Healthy_life_expectancy": "69.35",
        "Corruption": "0.834",
        "Id": "35",
        "Freedom_Score": "63.1",
        "Property_Rights": "44.9",
        "Government_Spending": "66",
        "Business": "72.2",
        "Trade": "75.8",
        "Investment": "80",
        "rank": "30",
        "Crime_Index": "57",
        "Population": "52085168"
    },
    {
        "Country": "Costa Rica",
        "Happiness_Score": "6.609",
        "GDP_per_capita": "9.952",
        "Social_support": "0.872",
        "Healthy_life_expectancy": "70",
        "Corruption": "0.768",
        "Id": "39",
        "Freedom_Score": "66.5",
        "Property_Rights": "66",
        "Government_Spending": "85.9",
        "Business": "73.8",
        "Trade": "74.6",
        "Investment": "70",
        "rank": "38",
        "Crime_Index": "54",
        "Population": "5212173"
    },
    {
        "Country": "Croatia",
        "Happiness_Score": "6.125",
        "GDP_per_capita": "10.341",
        "Social_support": "0.917",
        "Healthy_life_expectancy": "68.95",
        "Corruption": "0.925",
        "Id": "41",
        "Freedom_Score": "66.4",
        "Property_Rights": "79.5",
        "Government_Spending": "25.1",
        "Business": "72.1",
        "Trade": "78.6",
        "Investment": "75",
        "rank": "123",
        "Crime_Index": "25",
        "Population": "4008617"
    },
    {
        "Country": "Cyprus",
        "Happiness_Score": "6.13",
        "GDP_per_capita": "10.611",
        "Social_support": "0.826",
        "Healthy_life_expectancy": "72.802",
        "Corruption": "0.86",
        "Id": "43",
        "Freedom_Score": "72.3",
        "Property_Rights": "83",
        "Government_Spending": "45.8",
        "Business": "74.9",
        "Trade": "78.6",
        "Investment": "75",
        "rank": "105",
        "Crime_Index": "31",
        "Population": "1260138"
    },
    {
        "Country": "Czech Republic",
        "Happiness_Score": "6.845",
        "GDP_per_capita": "10.611",
        "Social_support": "0.953",
        "Healthy_life_expectancy": "69.05",
        "Corruption": "0.859",
        "Id": "44",
        "Freedom_Score": "71.9",
        "Property_Rights": "88.5",
        "Government_Spending": "39.5",
        "Business": "76.9",
        "Trade": "78.6",
        "Investment": "70",
        "rank": "120",
        "Crime_Index": "26",
        "Population": "10495295"
    },
    {
        "Country": "Denmark",
        "Happiness_Score": "7.586",
        "GDP_per_capita": "10.962",
        "Social_support": "0.954",
        "Healthy_life_expectancy": "71.25",
        "Corruption": "0.196",
        "Id": "45",
        "Freedom_Score": "77.6",
        "Property_Rights": "97.5",
        "Government_Spending": "20.9",
        "Business": "89",
        "Trade": "78.6",
        "Investment": "90",
        "rank": "117",
        "Crime_Index": "26",
        "Population": "5910913"
    },
    {
        "Country": "Dominican Republic",
        "Happiness_Score": "5.569",
        "GDP_per_capita": "9.811",
        "Social_support": "0.827",
        "Healthy_life_expectancy": "64.399",
        "Corruption": "0.657",
        "Id": "48",
        "Freedom_Score": "62.6",
        "Property_Rights": "55.1",
        "Government_Spending": "89.1",
        "Business": "72.1",
        "Trade": "67",
        "Investment": "70",
        "rank": "22",
        "Crime_Index": "61",
        "Population": "11332972"
    },
    {
        "Country": "Ecuador",
        "Happiness_Score": "5.559",
        "GDP_per_capita": "9.27",
        "Social_support": "0.806",
        "Healthy_life_expectancy": "69",
        "Corruption": "0.833",
        "Id": "49",
        "Freedom_Score": "55",
        "Property_Rights": "31.6",
        "Government_Spending": "60.3",
        "Business": "64",
        "Trade": "65.6",
        "Investment": "35",
        "rank": "37",
        "Crime_Index": "55",
        "Population": "18190484"
    },
    {
        "Country": "Egypt",
        "Happiness_Score": "4.17",
        "GDP_per_capita": "9.367",
        "Social_support": "0.726",
        "Healthy_life_expectancy": "63.503",
        "Corruption": "0.58",
        "Id": "50",
        "Freedom_Score": "49.6",
        "Property_Rights": "39.7",
        "Government_Spending": "79.4",
        "Business": "51.1",
        "Trade": "60.2",
        "Investment": "65",
        "rank": "59",
        "Crime_Index": "47",
        "Population": "112716598"
    },
    {
        "Country": "El Salvador",
        "Happiness_Score": "6.122",
        "GDP_per_capita": "9.089",
        "Social_support": "0.755",
        "Healthy_life_expectancy": "65.597",
        "Corruption": "0.62",
        "Id": "51",
        "Freedom_Score": "56",
        "Property_Rights": "43",
        "Government_Spending": "71.6",
        "Business": "64.7",
        "Trade": "68.6",
        "Investment": "60",
        "rank": "8",
        "Crime_Index": "68",
        "Population": "6364943"
    },
    {
        "Country": "Estonia",
        "Happiness_Score": "6.455",
        "GDP_per_capita": "10.541",
        "Social_support": "0.946",
        "Healthy_life_expectancy": "69.65",
        "Corruption": "0.409",
        "Id": "54",
        "Freedom_Score": "78.6",
        "Property_Rights": "92.1",
        "Government_Spending": "47.5",
        "Business": "79.4",
        "Trade": "78.6",
        "Investment": "90",
        "rank": "125",
        "Crime_Index": "24",
        "Population": "1322765"
    },
    {
        "Country": "Ethiopia",
        "Happiness_Score": "4.091",
        "GDP_per_capita": "7.739",
        "Social_support": "0.782",
        "Healthy_life_expectancy": "60.698",
        "Corruption": "0.789",
        "Id": "55",
        "Freedom_Score": "48.3",
        "Property_Rights": "30.4",
        "Government_Spending": "93.7",
        "Business": "39.3",
        "Trade": "56.4",
        "Investment": "30",
        "rank": "50",
        "Crime_Index": "49",
        "Population": "126527060"
    },
    {
        "Country": "Finland",
        "Happiness_Score": "7.804",
        "GDP_per_capita": "10.792",
        "Social_support": "0.969",
        "Healthy_life_expectancy": "71.15",
        "Corruption": "0.182",
        "Id": "57",
        "Freedom_Score": "77.1",
        "Property_Rights": "100",
        "Government_Spending": "8.5",
        "Business": "84.9",
        "Trade": "78.6",
        "Investment": "85",
        "rank": "114",
        "Crime_Index": "28",
        "Population": "5545475"
    },
    {
        "Country": "France",
        "Happiness_Score": "6.661",
        "GDP_per_capita": "10.701",
        "Social_support": "0.909",
        "Healthy_life_expectancy": "72.3",
        "Corruption": "0.553",
        "Id": "58",
        "Freedom_Score": "63.6",
        "Property_Rights": "93",
        "Government_Spending": "0.1",
        "Business": "78.2",
        "Trade": "78.6",
        "Investment": "75",
        "rank": "44",
        "Crime_Index": "52",
        "Population": "64756584"
    },
    {
        "Country": "Georgia",
        "Happiness_Score": "5.109",
        "GDP_per_capita": "9.646",
        "Social_support": "0.716",
        "Healthy_life_expectancy": "64.95",
        "Corruption": "0.649",
        "Id": "61",
        "Freedom_Score": "68.7",
        "Property_Rights": "54.3",
        "Government_Spending": "70",
        "Business": "69.8",
        "Trade": "86",
        "Investment": "80",
        "rank": "126",
        "Crime_Index": "23",
        "Population": "3728282"
    },
    {
        "Country": "Germany",
        "Happiness_Score": "6.892",
        "GDP_per_capita": "10.879",
        "Social_support": "0.896",
        "Healthy_life_expectancy": "71.3",
        "Corruption": "0.42",
        "Id": "62",
        "Freedom_Score": "73.7",
        "Property_Rights": "94.8",
        "Government_Spending": "28.3",
        "Business": "79.7",
        "Trade": "78.6",
        "Investment": "80",
        "rank": "95",
        "Crime_Index": "36",
        "Population": "83294633"
    },
    {
        "Country": "Ghana",
        "Happiness_Score": "4.605",
        "GDP_per_capita": "8.596",
        "Social_support": "0.641",
        "Healthy_life_expectancy": "58.763",
        "Corruption": "0.881",
        "Id": "63",
        "Freedom_Score": "58",
        "Property_Rights": "50.5",
        "Government_Spending": "81.2",
        "Business": "53.3",
        "Trade": "63",
        "Investment": "70",
        "rank": "58",
        "Crime_Index": "47",
        "Population": "34121985"
    },
    {
        "Country": "Greece",
        "Happiness_Score": "5.931",
        "GDP_per_capita": "10.288",
        "Social_support": "0.835",
        "Healthy_life_expectancy": "71.15",
        "Corruption": "0.793",
        "Id": "64",
        "Freedom_Score": "56.9",
        "Property_Rights": "76.7",
        "Government_Spending": "9.7",
        "Business": "70.3",
        "Trade": "78.6",
        "Investment": "55",
        "rank": "66",
        "Crime_Index": "46",
        "Population": "10341277"
    },
    {
        "Country": "Guatemala",
        "Happiness_Score": "6.15",
        "GDP_per_capita": "9.116",
        "Social_support": "0.812",
        "Healthy_life_expectancy": "62.9",
        "Corruption": "0.837",
        "Id": "65",
        "Freedom_Score": "62.7",
        "Property_Rights": "39.2",
        "Government_Spending": "94",
        "Business": "65.8",
        "Trade": "74.6",
        "Investment": "70",
        "rank": "26",
        "Crime_Index": "59",
        "Population": "18092026"
    },
    {
        "Country": "Honduras",
        "Happiness_Score": "6.023",
        "GDP_per_capita": "8.635",
        "Social_support": "0.766",
        "Healthy_life_expectancy": "64.063",
        "Corruption": "0.843",
        "Id": "70",
        "Freedom_Score": "58.7",
        "Property_Rights": "38.3",
        "Government_Spending": "77.5",
        "Business": "60.8",
        "Trade": "71.6",
        "Investment": "65",
        "rank": "5",
        "Crime_Index": "75",
        "Population": "10593798"
    },
    {
        "Country": "Hungary",
        "Happiness_Score": "6.041",
        "GDP_per_capita": "10.419",
        "Social_support": "0.943",
        "Healthy_life_expectancy": "67.5",
        "Corruption": "0.839",
        "Id": "72",
        "Freedom_Score": "64.1",
        "Property_Rights": "69.5",
        "Government_Spending": "29.8",
        "Business": "73.5",
        "Trade": "78.6",
        "Investment": "80",
        "rank": "96",
        "Crime_Index": "34",
        "Population": "10156239"
    },
    {
        "Country": "Iceland",
        "Happiness_Score": "7.53",
        "GDP_per_capita": "10.896",
        "Social_support": "0.983",
        "Healthy_life_expectancy": "72.05",
        "Corruption": "0.668",
        "Id": "73",
        "Freedom_Score": "72.2",
        "Property_Rights": "96.8",
        "Government_Spending": "31.5",
        "Business": "83.3",
        "Trade": "80.4",
        "Investment": "80",
        "rank": "124",
        "Crime_Index": "24",
        "Population": "375318"
    },
    {
        "Country": "India",
        "Happiness_Score": "4.036",
        "GDP_per_capita": "8.759",
        "Social_support": "0.608",
        "Healthy_life_expectancy": "60.777",
        "Corruption": "0.774",
        "Id": "74",
        "Freedom_Score": "52.9",
        "Property_Rights": "49.7",
        "Government_Spending": "73.8",
        "Business": "64.3",
        "Trade": "59.8",
        "Investment": "40",
        "rank": "71",
        "Crime_Index": "44",
        "Population": "1428627663"
    },
    {
        "Country": "Indonesia",
        "Happiness_Score": "5.277",
        "GDP_per_capita": "9.385",
        "Social_support": "0.804",
        "Healthy_life_expectancy": "63.048",
        "Corruption": "0.876",
        "Id": "75",
        "Freedom_Score": "63.5",
        "Property_Rights": "38.5",
        "Government_Spending": "90.6",
        "Business": "70.6",
        "Trade": "78.8",
        "Investment": "50",
        "rank": "65",
        "Crime_Index": "46",
        "Population": "277534122"
    },
    {
        "Country": "Iran",
        "Happiness_Score": "4.876",
        "GDP_per_capita": "9.61",
        "Social_support": "0.778",
        "Healthy_life_expectancy": "66.6",
        "Corruption": "0.747",
        "Id": "76",
        "Freedom_Score": "42.2",
        "Property_Rights": "25",
        "Government_Spending": "94.8",
        "Business": "38.9",
        "Trade": "55.8",
        "Investment": "5",
        "rank": "48",
        "Crime_Index": "49",
        "Population": "89172767"
    },
    {
        "Country": "Iraq",
        "Happiness_Score": "4.941",
        "GDP_per_capita": "9.098",
        "Social_support": "0.718",
        "Healthy_life_expectancy": "63.415",
        "Corruption": "0.876",
        "Id": "77",
        "Freedom_Score": "0",
        "Property_Rights": "14.6",
        "Government_Spending": "0",
        "Business": "43.1",
        "Trade": "0",
        "Investment": "0",
        "rank": "53",
        "Crime_Index": "48",
        "Population": "45504560"
    },
    {
        "Country": "Ireland",
        "Happiness_Score": "6.911",
        "GDP_per_capita": "11.527",
        "Social_support": "0.905",
        "Healthy_life_expectancy": "71.3",
        "Corruption": "0.358",
        "Id": "78",
        "Freedom_Score": "82",
        "Property_Rights": "92.9",
        "Government_Spending": "80.5",
        "Business": "87.2",
        "Trade": "78.6",
        "Investment": "90",
        "rank": "67",
        "Crime_Index": "46",
        "Population": "5056935"
    },
    {
        "Country": "Israel",
        "Happiness_Score": "7.473",
        "GDP_per_capita": "10.639",
        "Social_support": "0.943",
        "Healthy_life_expectancy": "72.697",
        "Corruption": "0.708",
        "Id": "79",
        "Freedom_Score": "68.9",
        "Property_Rights": "82.3",
        "Government_Spending": "49.1",
        "Business": "84.9",
        "Trade": "82.6",
        "Investment": "80",
        "rank": "104",
        "Crime_Index": "31",
        "Population": "9174520"
    },
    {
        "Country": "Italy",
        "Happiness_Score": "6.405",
        "GDP_per_capita": "10.634",
        "Social_support": "0.882",
        "Healthy_life_expectancy": "72.05",
        "Corruption": "0.842",
        "Id": "80",
        "Freedom_Score": "62.3",
        "Property_Rights": "81.2",
        "Government_Spending": "13.7",
        "Business": "73.8",
        "Trade": "78.6",
        "Investment": "80",
        "rank": "69",
        "Crime_Index": "45",
        "Population": "58870762"
    },
    {
        "Country": "Jamaica",
        "Happiness_Score": "5.703",
        "GDP_per_capita": "9.165",
        "Social_support": "0.867",
        "Healthy_life_expectancy": "66.6",
        "Corruption": "0.875",
        "Id": "81",
        "Freedom_Score": "68.1",
        "Property_Rights": "65.8",
        "Government_Spending": "72.2",
        "Business": "67.7",
        "Trade": "70",
        "Investment": "70",
        "rank": "10",
        "Crime_Index": "67",
        "Population": "2825544"
    },
    {
        "Country": "Japan",
        "Happiness_Score": "6.129",
        "GDP_per_capita": "10.616",
        "Social_support": "0.894",
        "Healthy_life_expectancy": "74.349",
        "Corruption": "0.64",
        "Id": "82",
        "Freedom_Score": "69.3",
        "Property_Rights": "94.1",
        "Government_Spending": "48.4",
        "Business": "78.3",
        "Trade": "75.2",
        "Investment": "60",
        "rank": "129",
        "Crime_Index": "22",
        "Population": "123294513"
    },
    {
        "Country": "Jordan",
        "Happiness_Score": "4.12",
        "GDP_per_capita": "9.13",
        "Social_support": "0.729",
        "Healthy_life_expectancy": "67.6",
        "Corruption": "0.687",
        "Id": "83",
        "Freedom_Score": "58.8",
        "Property_Rights": "54.1",
        "Government_Spending": "70",
        "Business": "59.8",
        "Trade": "71.4",
        "Investment": "70",
        "rank": "87",
        "Crime_Index": "40",
        "Population": "11337052"
    },
    {
        "Country": "Kazakhstan",
        "Happiness_Score": "6.144",
        "GDP_per_capita": "10.166",
        "Social_support": "0.931",
        "Healthy_life_expectancy": "65.802",
        "Corruption": "0.721",
        "Id": "84",
        "Freedom_Score": "62.1",
        "Property_Rights": "54.8",
        "Government_Spending": "85.1",
        "Business": "64.6",
        "Trade": "74.8",
        "Investment": "50",
        "rank": "40",
        "Crime_Index": "54",
        "Population": "19606633"
    },
    {
        "Country": "Kenya",
        "Happiness_Score": "4.487",
        "GDP_per_capita": "8.458",
        "Social_support": "0.69",
        "Healthy_life_expectancy": "58.499",
        "Corruption": "0.852",
        "Id": "85",
        "Freedom_Score": "52.5",
        "Property_Rights": "39.7",
        "Government_Spending": "81.7",
        "Business": "56",
        "Trade": "57.2",
        "Investment": "55",
        "rank": "23",
        "Crime_Index": "60",
        "Population": "55100586"
    },
    {
        "Country": "South Korea",
        "Happiness_Score": "5.951",
        "GDP_per_capita": "10.693",
        "Social_support": "0.812",
        "Healthy_life_expectancy": "73.65",
        "Corruption": "0.701",
        "Id": "88",
        "Freedom_Score": "73.7",
        "Property_Rights": "88.5",
        "Government_Spending": "82",
        "Business": "84.8",
        "Trade": "72.2",
        "Investment": "60",
        "rank": "116",
        "Crime_Index": "27",
        "Population": "51784059"
    },
    {
        "Country": "Kyrgyzstan",
        "Happiness_Score": "5.825",
        "GDP_per_capita": "8.486",
        "Social_support": "0.911",
        "Healthy_life_expectancy": "66.852",
        "Corruption": "0.904",
        "Id": "90",
        "Freedom_Score": "55.8",
        "Property_Rights": "24.2",
        "Government_Spending": "66",
        "Business": "56.1",
        "Trade": "72",
        "Investment": "60",
        "rank": "31",
        "Crime_Index": "57",
        "Population": "6735347"
    },
    {
        "Country": "Latvia",
        "Happiness_Score": "6.213",
        "GDP_per_capita": "10.37",
        "Social_support": "0.937",
        "Healthy_life_expectancy": "66.4",
        "Corruption": "0.83",
        "Id": "92",
        "Freedom_Score": "72.8",
        "Property_Rights": "87.3",
        "Government_Spending": "49",
        "Business": "78.2",
        "Trade": "78.6",
        "Investment": "85",
        "rank": "91",
        "Crime_Index": "39",
        "Population": "1830211"
    },
    {
        "Country": "Lebanon",
        "Happiness_Score": "2.392",
        "GDP_per_capita": "9.478",
        "Social_support": "0.53",
        "Healthy_life_expectancy": "66.149",
        "Corruption": "0.891",
        "Id": "93",
        "Freedom_Score": "45.6",
        "Property_Rights": "33.1",
        "Government_Spending": "80.7",
        "Business": "48.1",
        "Trade": "71.4",
        "Investment": "30",
        "rank": "60",
        "Crime_Index": "47",
        "Population": "5353930"
    },
    {
        "Country": "Lithuania",
        "Happiness_Score": "6.763",
        "GDP_per_capita": "10.568",
        "Social_support": "0.939",
        "Healthy_life_expectancy": "67.397",
        "Corruption": "0.805",
        "Id": "98",
        "Freedom_Score": "72.2",
        "Property_Rights": "87.7",
        "Government_Spending": "56.9",
        "Business": "76",
        "Trade": "78.6",
        "Investment": "70",
        "rank": "101",
        "Crime_Index": "33",
        "Population": "2718352"
    },
    {
        "Country": "Luxembourg",
        "Happiness_Score": "7.228",
        "GDP_per_capita": "11.66",
        "Social_support": "0.879",
        "Healthy_life_expectancy": "71.675",
        "Corruption": "0.345",
        "Id": "99",
        "Freedom_Score": "78.4",
        "Property_Rights": "96.8",
        "Government_Spending": "41.6",
        "Business": "85.5",
        "Trade": "78.6",
        "Investment": "95",
        "rank": "97",
        "Crime_Index": "34",
        "Population": "654768"
    },
    {
        "Country": "North Macedonia",
        "Happiness_Score": "5.254",
        "GDP_per_capita": "9.703",
        "Social_support": "0.805",
        "Healthy_life_expectancy": "66.5",
        "Corruption": "0.902",
        "Id": "101",
        "Freedom_Score": "63.7",
        "Property_Rights": "58.9",
        "Government_Spending": "63.9",
        "Business": "74.1",
        "Trade": "77.8",
        "Investment": "65",
        "rank": "90",
        "Crime_Index": "39",
        "Population": "2085679"
    },
    {
        "Country": "Malaysia",
        "Happiness_Score": "6.012",
        "GDP_per_capita": "10.169",
        "Social_support": "0.799",
        "Healthy_life_expectancy": "65.662",
        "Corruption": "0.758",
        "Id": "104",
        "Freedom_Score": "67.3",
        "Property_Rights": "65.4",
        "Government_Spending": "82.4",
        "Business": "70.3",
        "Trade": "83",
        "Investment": "60",
        "rank": "29",
        "Crime_Index": "57",
        "Population": "34308525"
    },
    {
        "Country": "Malta",
        "Happiness_Score": "6.3",
        "GDP_per_capita": "10.661",
        "Social_support": "0.923",
        "Healthy_life_expectancy": "71.6",
        "Corruption": "0.729",
        "Id": "107",
        "Freedom_Score": "67.5",
        "Property_Rights": "86.9",
        "Government_Spending": "45.9",
        "Business": "75.5",
        "Trade": "78.6",
        "Investment": "70",
        "rank": "85",
        "Crime_Index": "40",
        "Population": "535064"
    },
    {
        "Country": "Mauritius",
        "Happiness_Score": "5.902",
        "GDP_per_capita": "9.957",
        "Social_support": "0.888",
        "Healthy_life_expectancy": "63.85",
        "Corruption": "0.775",
        "Id": "109",
        "Freedom_Score": "70.6",
        "Property_Rights": "87",
        "Government_Spending": "70.2",
        "Business": "76",
        "Trade": "87.8",
        "Investment": "80",
        "rank": "51",
        "Crime_Index": "49",
        "Population": "1300557"
    },
    {
        "Country": "Mexico",
        "Happiness_Score": "6.33",
        "GDP_per_capita": "9.85",
        "Social_support": "0.804",
        "Healthy_life_expectancy": "65.8",
        "Corruption": "0.768",
        "Id": "110",
        "Freedom_Score": "63.2",
        "Property_Rights": "47.8",
        "Government_Spending": "77.8",
        "Business": "72.4",
        "Trade": "76.8",
        "Investment": "75",
        "rank": "39",
        "Crime_Index": "54",
        "Population": "128455567"
    },
    {
        "Country": "Moldova",
        "Happiness_Score": "5.819",
        "GDP_per_capita": "9.499",
        "Social_support": "0.857",
        "Healthy_life_expectancy": "65.299",
        "Corruption": "0.901",
        "Id": "112",
        "Freedom_Score": "58.5",
        "Property_Rights": "37.9",
        "Government_Spending": "64.4",
        "Business": "60.2",
        "Trade": "75.6",
        "Investment": "55",
        "rank": "62",
        "Crime_Index": "46",
        "Population": "3435931"
    },
    {
        "Country": "Mongolia",
        "Happiness_Score": "5.84",
        "GDP_per_capita": "9.372",
        "Social_support": "0.933",
        "Healthy_life_expectancy": "60.5",
        "Corruption": "0.849",
        "Id": "113",
        "Freedom_Score": "61.7",
        "Property_Rights": "48.7",
        "Government_Spending": "64.1",
        "Business": "66.4",
        "Trade": "74.2",
        "Investment": "50",
        "rank": "34",
        "Crime_Index": "56",
        "Population": "3447157"
    },
    {
        "Country": "Montenegro",
        "Happiness_Score": "5.722",
        "GDP_per_capita": "9.813",
        "Social_support": "0.89",
        "Healthy_life_expectancy": "67.1",
        "Corruption": "0.844",
        "Id": "114",
        "Freedom_Score": "60.9",
        "Property_Rights": "59.7",
        "Government_Spending": "31.7",
        "Business": "67.3",
        "Trade": "79.2",
        "Investment": "75",
        "rank": "84",
        "Crime_Index": "41",
        "Population": "626485"
    },
    {
        "Country": "Morocco",
        "Happiness_Score": "4.903",
        "GDP_per_capita": "8.973",
        "Social_support": "0.553",
        "Healthy_life_expectancy": "63.901",
        "Corruption": "0.811",
        "Id": "115",
        "Freedom_Score": "58.4",
        "Property_Rights": "57.1",
        "Government_Spending": "72",
        "Business": "65.3",
        "Trade": "64.4",
        "Investment": "65",
        "rank": "52",
        "Crime_Index": "49",
        "Population": "37840044"
    },
    {
        "Country": "Namibia",
        "Happiness_Score": "4.631",
        "GDP_per_capita": "9.121",
        "Social_support": "0.787",
        "Healthy_life_expectancy": "56.851",
        "Corruption": "0.83",
        "Id": "117",
        "Freedom_Score": "57.7",
        "Property_Rights": "64",
        "Government_Spending": "53",
        "Business": "56",
        "Trade": "71.8",
        "Investment": "65",
        "rank": "15",
        "Crime_Index": "65",
        "Population": "2604172"
    },
    {
        "Country": "Nepal",
        "Happiness_Score": "5.36",
        "GDP_per_capita": "8.256",
        "Social_support": "0.748",
        "Healthy_life_expectancy": "61.847",
        "Corruption": "0.783",
        "Id": "118",
        "Freedom_Score": "51.4",
        "Property_Rights": "37.6",
        "Government_Spending": "77.2",
        "Business": "60.1",
        "Trade": "57.8",
        "Investment": "10",
        "rank": "94",
        "Crime_Index": "36",
        "Population": "30896590"
    },
    {
        "Country": "Netherlands",
        "Happiness_Score": "7.403",
        "GDP_per_capita": "10.942",
        "Social_support": "0.93",
        "Healthy_life_expectancy": "71.55",
        "Corruption": "0.379",
        "Id": "119",
        "Freedom_Score": "78",
        "Property_Rights": "95.6",
        "Government_Spending": "37.9",
        "Business": "84.4",
        "Trade": "78.6",
        "Investment": "90",
        "rank": "115",
        "Crime_Index": "27",
        "Population": "17618299"
    },
    {
        "Country": "New Zealand",
        "Happiness_Score": "7.123",
        "GDP_per_capita": "10.662",
        "Social_support": "0.952",
        "Healthy_life_expectancy": "70.35",
        "Corruption": "0.271",
        "Id": "120",
        "Freedom_Score": "78.9",
        "Property_Rights": "87.8",
        "Government_Spending": "49.7",
        "Business": "88.8",
        "Trade": "90.4",
        "Investment": "70",
        "rank": "77",
        "Crime_Index": "43",
        "Population": "5228100"
    },
    {
        "Country": "Nicaragua",
        "Happiness_Score": "6.259",
        "GDP_per_capita": "8.618",
        "Social_support": "0.853",
        "Healthy_life_expectancy": "65.65",
        "Corruption": "0.625",
        "Id": "121",
        "Freedom_Score": "54.9",
        "Property_Rights": "29.7",
        "Government_Spending": "74.4",
        "Business": "53.9",
        "Trade": "66.4",
        "Investment": "60",
        "rank": "55",
        "Crime_Index": "48",
        "Population": "7046310"
    },
    {
        "Country": "Nigeria",
        "Happiness_Score": "4.981",
        "GDP_per_capita": "8.496",
        "Social_support": "0.74",
        "Healthy_life_expectancy": "54.891",
        "Corruption": "0.911",
        "Id": "123",
        "Freedom_Score": "53.9",
        "Property_Rights": "24",
        "Government_Spending": "95.2",
        "Business": "44.3",
        "Trade": "68",
        "Investment": "45",
        "rank": "16",
        "Crime_Index": "64",
        "Population": "223804632"
    },
    {
        "Country": "Norway",
        "Happiness_Score": "7.315",
        "GDP_per_capita": "11.088",
        "Social_support": "0.943",
        "Healthy_life_expectancy": "71.5",
        "Corruption": "0.283",
        "Id": "124",
        "Freedom_Score": "76.9",
        "Property_Rights": "98.9",
        "Government_Spending": "18.7",
        "Business": "95.2",
        "Trade": "84.6",
        "Investment": "75",
        "rank": "98",
        "Crime_Index": "34",
        "Population": "5474360"
    },
    {
        "Country": "Pakistan",
        "Happiness_Score": "4.555",
        "GDP_per_capita": "8.54",
        "Social_support": "0.601",
        "Healthy_life_expectancy": "57.313",
        "Corruption": "0.787",
        "Id": "126",
        "Freedom_Score": "49.4",
        "Property_Rights": "29",
        "Government_Spending": "88.9",
        "Business": "45.9",
        "Trade": "65.8",
        "Investment": "60",
        "rank": "79",
        "Crime_Index": "43",
        "Population": "240485658"
    },
    {
        "Country": "Panama",
        "Happiness_Score": "6.265",
        "GDP_per_capita": "10.305",
        "Social_support": "0.896",
        "Healthy_life_expectancy": "68.95",
        "Corruption": "0.878",
        "Id": "127",
        "Freedom_Score": "63.8",
        "Property_Rights": "56.8",
        "Government_Spending": "81.1",
        "Business": "71.1",
        "Trade": "78.5",
        "Investment": "75",
        "rank": "68",
        "Crime_Index": "45",
        "Population": "4468087"
    },
    {
        "Country": "Paraguay",
        "Happiness_Score": "5.738",
        "GDP_per_capita": "9.51",
        "Social_support": "0.906",
        "Healthy_life_expectancy": "65.9",
        "Corruption": "0.843",
        "Id": "129",
        "Freedom_Score": "61",
        "Property_Rights": "46.8",
        "Government_Spending": "81.7",
        "Business": "69.5",
        "Trade": "77.2",
        "Investment": "75",
        "rank": "49",
        "Crime_Index": "49",
        "Population": "6861524"
    },
    {
        "Country": "Peru",
        "Happiness_Score": "5.526",
        "GDP_per_capita": "9.402",
        "Social_support": "0.798",
        "Healthy_life_expectancy": "69.85",
        "Corruption": "0.892",
        "Id": "130",
        "Freedom_Score": "66.5",
        "Property_Rights": "51.4",
        "Government_Spending": "83.3",
        "Business": "72.8",
        "Trade": "81.2",
        "Investment": "75",
        "rank": "12",
        "Crime_Index": "67",
        "Population": "34352719"
    },
    {
        "Country": "Philippines",
        "Happiness_Score": "5.523",
        "GDP_per_capita": "8.979",
        "Social_support": "0.78",
        "Healthy_life_expectancy": "62.038",
        "Corruption": "0.732",
        "Id": "131",
        "Freedom_Score": "59.3",
        "Property_Rights": "46.4",
        "Government_Spending": "81.3",
        "Business": "66.1",
        "Trade": "74.4",
        "Investment": "60",
        "rank": "80",
        "Crime_Index": "42",
        "Population": "117337368"
    },
    {
        "Country": "Poland",
        "Happiness_Score": "6.26",
        "GDP_per_capita": "10.453",
        "Social_support": "0.925",
        "Healthy_life_expectancy": "69.049",
        "Corruption": "0.736",
        "Id": "132",
        "Freedom_Score": "67.7",
        "Property_Rights": "72.7",
        "Government_Spending": "40",
        "Business": "74.8",
        "Trade": "78.6",
        "Investment": "80",
        "rank": "106",
        "Crime_Index": "31",
        "Population": "41026067"
    },
    {
        "Country": "Portugal",
        "Happiness_Score": "5.968",
        "GDP_per_capita": "10.429",
        "Social_support": "0.878",
        "Healthy_life_expectancy": "71.25",
        "Corruption": "0.878",
        "Id": "133",
        "Freedom_Score": "69.5",
        "Property_Rights": "89.9",
        "Government_Spending": "34.7",
        "Business": "76.2",
        "Trade": "78.6",
        "Investment": "70",
        "rank": "109",
        "Crime_Index": "30",
        "Population": "10247605"
    },
    {
        "Country": "Romania",
        "Happiness_Score": "6.589",
        "GDP_per_capita": "10.339",
        "Social_support": "0.848",
        "Healthy_life_expectancy": "67.051",
        "Corruption": "0.929",
        "Id": "135",
        "Freedom_Score": "64.5",
        "Property_Rights": "81",
        "Government_Spending": "59.7",
        "Business": "71.3",
        "Trade": "78.6",
        "Investment": "70",
        "rank": "112",
        "Crime_Index": "28",
        "Population": "19892812"
    },
    {
        "Country": "Russia",
        "Happiness_Score": "5.661",
        "GDP_per_capita": "10.21",
        "Social_support": "0.889",
        "Healthy_life_expectancy": "64.947",
        "Corruption": "0.801",
        "Id": "136",
        "Freedom_Score": "53.8",
        "Property_Rights": "30.6",
        "Government_Spending": "60.4",
        "Business": "54.8",
        "Trade": "69.4",
        "Investment": "30",
        "rank": "86",
        "Crime_Index": "40",
        "Population": "144444359"
    },
    {
        "Country": "Saudi Arabia",
        "Happiness_Score": "6.463",
        "GDP_per_capita": "10.715",
        "Social_support": "0.884",
        "Healthy_life_expectancy": "64.399",
        "Corruption": "0.691",
        "Id": "142",
        "Freedom_Score": "58.3",
        "Property_Rights": "47.3",
        "Government_Spending": "60.3",
        "Business": "71.8",
        "Trade": "74.2",
        "Investment": "50",
        "rank": "121",
        "Crime_Index": "25",
        "Population": "36947025"
    },
    {
        "Country": "Serbia",
        "Happiness_Score": "6.144",
        "GDP_per_capita": "9.854",
        "Social_support": "0.873",
        "Healthy_life_expectancy": "67.088",
        "Corruption": "0.816",
        "Id": "144",
        "Freedom_Score": "63.5",
        "Property_Rights": "58.7",
        "Government_Spending": "37.6",
        "Business": "74.3",
        "Trade": "76",
        "Investment": "70",
        "rank": "93",
        "Crime_Index": "38",
        "Population": "7149077"
    },
    {
        "Country": "Singapore",
        "Happiness_Score": "6.587",
        "GDP_per_capita": "11.571",
        "Social_support": "0.878",
        "Healthy_life_expectancy": "73.8",
        "Corruption": "0.146",
        "Id": "147",
        "Freedom_Score": "83.9",
        "Property_Rights": "94",
        "Government_Spending": "89",
        "Business": "86.9",
        "Trade": "95",
        "Investment": "85",
        "rank": "113",
        "Crime_Index": "28",
        "Population": "6014723"
    },
    {
        "Country": "Slovakia",
        "Happiness_Score": "6.469",
        "GDP_per_capita": "10.353",
        "Social_support": "0.953",
        "Healthy_life_expectancy": "68.838",
        "Corruption": "0.898",
        "Id": "148",
        "Freedom_Score": "69",
        "Property_Rights": "84.2",
        "Government_Spending": "41.2",
        "Business": "72.2",
        "Trade": "78.6",
        "Investment": "75",
        "rank": "107",
        "Crime_Index": "30",
        "Population": "5795199"
    },
    {
        "Country": "Slovenia",
        "Happiness_Score": "6.65",
        "GDP_per_capita": "10.588",
        "Social_support": "0.951",
        "Healthy_life_expectancy": "71.052",
        "Corruption": "0.771",
        "Id": "149",
        "Freedom_Score": "68.5",
        "Property_Rights": "88.6",
        "Government_Spending": "31.5",
        "Business": "75.9",
        "Trade": "78.6",
        "Investment": "70",
        "rank": "128",
        "Crime_Index": "22",
        "Population": "2119675"
    },
    {
        "Country": "South Africa",
        "Happiness_Score": "5.275",
        "GDP_per_capita": "9.478",
        "Social_support": "0.907",
        "Healthy_life_expectancy": "56.989",
        "Corruption": "0.902",
        "Id": "151",
        "Freedom_Score": "55.7",
        "Property_Rights": "42.5",
        "Government_Spending": "67.3",
        "Business": "64.5",
        "Trade": "72.4",
        "Investment": "45",
        "rank": "3",
        "Crime_Index": "77",
        "Population": "60414495"
    },
    {
        "Country": "Spain",
        "Happiness_Score": "6.436",
        "GDP_per_capita": "10.54",
        "Social_support": "0.932",
        "Healthy_life_expectancy": "72.35",
        "Corruption": "0.711",
        "Id": "152",
        "Freedom_Score": "65",
        "Property_Rights": "87.2",
        "Government_Spending": "30.2",
        "Business": "75.2",
        "Trade": "83.6",
        "Investment": "85",
        "rank": "102",
        "Crime_Index": "33",
        "Population": "47519628"
    },
    {
        "Country": "Sri Lanka",
        "Happiness_Score": "4.442",
        "GDP_per_capita": "9.491",
        "Social_support": "0.826",
        "Healthy_life_expectancy": "67.15",
        "Corruption": "0.808",
        "Id": "153",
        "Freedom_Score": "52.2",
        "Property_Rights": "51.6",
        "Government_Spending": "88",
        "Business": "54.4",
        "Trade": "67.2",
        "Investment": "30",
        "rank": "83",
        "Crime_Index": "41",
        "Population": "21893579"
    },
    {
        "Country": "Sweden",
        "Happiness_Score": "7.395",
        "GDP_per_capita": "10.883",
        "Social_support": "0.939",
        "Healthy_life_expectancy": "72.15",
        "Corruption": "0.202",
        "Id": "157",
        "Freedom_Score": "77.5",
        "Property_Rights": "96.6",
        "Government_Spending": "26.2",
        "Business": "84.6",
        "Trade": "78.6",
        "Investment": "85",
        "rank": "54",
        "Crime_Index": "48",
        "Population": "10612086"
    },
    {
        "Country": "Switzerland",
        "Happiness_Score": "7.24",
        "GDP_per_capita": "11.164",
        "Social_support": "0.92",
        "Healthy_life_expectancy": "72.9",
        "Corruption": "0.266",
        "Id": "158",
        "Freedom_Score": "83.8",
        "Property_Rights": "94.2",
        "Government_Spending": "63.9",
        "Business": "84.3",
        "Trade": "86.6",
        "Investment": "85",
        "rank": "131",
        "Crime_Index": "22",
        "Population": "8796669"
    },
    {
        "Country": "Taiwan",
        "Happiness_Score": "6.535",
        "GDP_per_capita": "10.797",
        "Social_support": "0.884",
        "Healthy_life_expectancy": "69.6",
        "Corruption": "0.681",
        "Id": "160",
        "Freedom_Score": "80.7",
        "Property_Rights": "81.9",
        "Government_Spending": "91.1",
        "Business": "84.3",
        "Trade": "85.8",
        "Investment": "70",
        "rank": "134",
        "Crime_Index": "15",
        "Population": "23923276"
    },
    {
        "Country": "Tanzania",
        "Happiness_Score": "3.694",
        "GDP_per_capita": "7.857",
        "Social_support": "0.653",
        "Healthy_life_expectancy": "59.401",
        "Corruption": "0.554",
        "Id": "162",
        "Freedom_Score": "60",
        "Property_Rights": "44.8",
        "Government_Spending": "91.3",
        "Business": "50.1",
        "Trade": "60.6",
        "Investment": "55",
        "rank": "35",
        "Crime_Index": "56",
        "Population": "67438106"
    },
    {
        "Country": "Thailand",
        "Happiness_Score": "5.843",
        "GDP_per_capita": "9.751",
        "Social_support": "0.874",
        "Healthy_life_expectancy": "68.45",
        "Corruption": "0.91",
        "Id": "163",
        "Freedom_Score": "60.6",
        "Property_Rights": "44.2",
        "Government_Spending": "81.5",
        "Business": "66.6",
        "Trade": "70.8",
        "Investment": "55",
        "rank": "89",
        "Crime_Index": "39",
        "Population": "71801279"
    },
    {
        "Country": "Tunisia",
        "Happiness_Score": "4.497",
        "GDP_per_capita": "9.244",
        "Social_support": "0.73",
        "Healthy_life_expectancy": "67",
        "Corruption": "0.907",
        "Id": "168",
        "Freedom_Score": "52.9",
        "Property_Rights": "61.8",
        "Government_Spending": "68.4",
        "Business": "54.4",
        "Trade": "66.3",
        "Investment": "40",
        "rank": "73",
        "Crime_Index": "44",
        "Population": "12458223"
    },
    {
        "Country": "Turkey",
        "Happiness_Score": "4.614",
        "GDP_per_capita": "10.307",
        "Social_support": "0.796",
        "Healthy_life_expectancy": "68.663",
        "Corruption": "0.795",
        "Id": "169",
        "Freedom_Score": "56.9",
        "Property_Rights": "40.8",
        "Government_Spending": "66.1",
        "Business": "59.7",
        "Trade": "75.8",
        "Investment": "70",
        "rank": "88",
        "Crime_Index": "40",
        "Population": "85816199"
    },
    {
        "Country": "Uganda",
        "Happiness_Score": "4.432",
        "GDP_per_capita": "7.716",
        "Social_support": "0.794",
        "Healthy_life_expectancy": "58.913",
        "Corruption": "0.857",
        "Id": "171",
        "Freedom_Score": "51.4",
        "Property_Rights": "47.7",
        "Government_Spending": "87.4",
        "Business": "46.1",
        "Trade": "55.4",
        "Investment": "55",
        "rank": "32",
        "Crime_Index": "56",
        "Population": "48582334"
    },
    {
        "Country": "Ukraine",
        "Happiness_Score": "5.071",
        "GDP_per_capita": "9.314",
        "Social_support": "0.878",
        "Healthy_life_expectancy": "64.55",
        "Corruption": "0.907",
        "Id": "172",
        "Freedom_Score": "0",
        "Property_Rights": "0",
        "Government_Spending": "0",
        "Business": "0",
        "Trade": "0",
        "Investment": "0",
        "rank": "57",
        "Crime_Index": "47",
        "Population": "36744634"
    },
    {
        "Country": "United Arab Emirates",
        "Happiness_Score": "6.571",
        "GDP_per_capita": "11.145",
        "Social_support": "0.826",
        "Healthy_life_expectancy": "66.243",
        "Corruption": "0.584",
        "Id": "173",
        "Freedom_Score": "70.9",
        "Property_Rights": "65.4",
        "Government_Spending": "71.6",
        "Business": "77",
        "Trade": "78",
        "Investment": "50",
        "rank": "135",
        "Crime_Index": "15",
        "Population": "9516871"
    },
    {
        "Country": "United Kingdom",
        "Happiness_Score": "6.796",
        "GDP_per_capita": "10.704",
        "Social_support": "0.882",
        "Healthy_life_expectancy": "70.3",
        "Corruption": "0.454",
        "Id": "174",
        "Freedom_Score": "69.9",
        "Property_Rights": "95.1",
        "Government_Spending": "41.9",
        "Business": "79.1",
        "Trade": "81.8",
        "Investment": "80",
        "rank": "64",
        "Crime_Index": "46",
        "Population": "67736802"
    },
    {
        "Country": "United States",
        "Happiness_Score": "6.894",
        "GDP_per_capita": "11.048",
        "Social_support": "0.919",
        "Healthy_life_expectancy": "65.85",
        "Corruption": "0.689",
        "Id": "175",
        "Freedom_Score": "70.6",
        "Property_Rights": "94.7",
        "Government_Spending": "49.3",
        "Business": "83.8",
        "Trade": "75.4",
        "Investment": "85",
        "rank": "56",
        "Crime_Index": "48",
        "Population": "339996563"
    },
    {
        "Country": "Uruguay",
        "Happiness_Score": "6.494",
        "GDP_per_capita": "10.037",
        "Social_support": "0.913",
        "Healthy_life_expectancy": "67.5",
        "Corruption": "0.575",
        "Id": "176",
        "Freedom_Score": "70.2",
        "Property_Rights": "84.3",
        "Government_Spending": "70.1",
        "Business": "80.1",
        "Trade": "70.8",
        "Investment": "70",
        "rank": "45",
        "Crime_Index": "52",
        "Population": "3423108"
    },
    {
        "Country": "Uzbekistan",
        "Happiness_Score": "6.014",
        "GDP_per_capita": "8.948",
        "Social_support": "0.875",
        "Healthy_life_expectancy": "65.301",
        "Corruption": "0.638",
        "Id": "177",
        "Freedom_Score": "56.5",
        "Property_Rights": "30.9",
        "Government_Spending": "74.9",
        "Business": "58.9",
        "Trade": "76",
        "Investment": "60",
        "rank": "99",
        "Crime_Index": "33",
        "Population": "35163944"
    },
    {
        "Country": "Venezuela",
        "Happiness_Score": "5.211",
        "GDP_per_capita": "5.527",
        "Social_support": "0.839",
        "Healthy_life_expectancy": "64.05",
        "Corruption": "0.811",
        "Id": "179",
        "Freedom_Score": "25.8",
        "Property_Rights": "0.1",
        "Government_Spending": "95",
        "Business": "30.8",
        "Trade": "42.3",
        "Investment": "0.1",
        "rank": "1",
        "Crime_Index": "84",
        "Population": "28838499"
    },
    {
        "Country": "Vietnam",
        "Happiness_Score": "5.763",
        "GDP_per_capita": "9.287",
        "Social_support": "0.821",
        "Healthy_life_expectancy": "65.502",
        "Corruption": "0.759",
        "Id": "180",
        "Freedom_Score": "61.8",
        "Property_Rights": "48.7",
        "Government_Spending": "86.5",
        "Business": "73.4",
        "Trade": "79.4",
        "Investment": "40",
        "rank": "63",
        "Crime_Index": "46",
        "Population": "98858950"
    },
    {
        "Country": "Zambia",
        "Happiness_Score": "3.982",
        "GDP_per_capita": "8.074",
        "Social_support": "0.694",
        "Healthy_life_expectancy": "55.032",
        "Corruption": "0.818",
        "Id": "182",
        "Freedom_Score": "47.8",
        "Property_Rights": "36",
        "Government_Spending": "69.6",
        "Business": "43.9",
        "Trade": "65.2",
        "Investment": "55",
        "rank": "74",
        "Crime_Index": "44",
        "Population": "20569737"
    },
    {
        "Country": "Zimbabwe",
        "Happiness_Score": "3.204",
        "GDP_per_capita": "7.641",
        "Social_support": "0.69",
        "Healthy_life_expectancy": "54.05",
        "Corruption": "0.766",
        "Id": "183",
        "Freedom_Score": "39",
        "Property_Rights": "20",
        "Government_Spending": "92.6",
        "Business": "39.8",
        "Trade": "54",
        "Investment": "25",
        "rank": "25",
        "Crime_Index": "59",
        "Population": "16665409"
    }
];